# How will this book teach computational biology?

<!-- TODO: update -->

>"The rise of computer programming, computational power, and modern statistical approaches may..." allow "...scientists to ask new questions and to extract more information from data than ever before." ([Touchon & McCoy 2016, Ecosphere](https://esajournals.onlinelibrary.wiley.com/doi/abs/10.1002/ecs2.1394))


## What you'll learn

### General skills that you'll learn

* **Statistical computing** using R, RStudio, and rmarkdown
* **Data analysis**, from t-tests to mixed models in R
* **Data visualization**, with an emphasis on ggplot2
* **Data science**, from data management best practices to data cleaning with dplyr
* **Computational reproducibility**, from formatting scripts to using rmarkdown to write reproducible reports

### Computational biology skills you'll learn

* Working with sequence data
* alignments
* Phylogenetics
* ...

## Teaching approach

* Always explore and visualize data
* Step-by-step instructions
* Frequently refreshing and review
* Comprehensive and self-contained
* Worked example
* "Modify this code" tasks
* Code completion tasks (key steps missing)
* Broken code tasks (fix non-functional code)
* Links to Jupyter notebooks (not yet implemented) 
* "Active Learning Notebooks" - all content and code in .Rmd format


## Requirements

* R
* RStudio
* External packages loaded via RStudio


## What's not in this book / course
