---
title: "Making flow charts with the diagram package"
author: "brouwern@gmail.com"
date: "January 31, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Annotated example from diagram vignette

From section "4. functions to create flow charts"

```{r}
library(diagram)

#Set margins
par(mar = c(1, 1, 1, 1))

#create empty plot window
openplotmat()

#coordinates estimtes location of plot elemens
## pos = is a vector of the number of elements PER ROW
elpos <- coordinates(pos = c(1, 1, 2, 4))

#..
fromto <- matrix(ncol = 2, byrow = TRUE,
                 data = c(1, 2,  #element 1 goes to elemtn 2
                          2, 3,  #element 2 goes to 3..
                          2, 4,  #and 4
                          4, 7,  #4 goes to 7
                          4, 8)) #and 8

#number of rows
nr <- nrow(fromto)

#matrix to hold arrow positions
arrpos <- matrix(ncol = 2, nrow = nr)


#loop to calculate arrow positions and plot them
for (i in 1:nr){
   arrpos[i, ] <- straightarrow(to   = elpos[fromto[i, 2], ],
                                from = elpos[fromto[i, 1], ],
                                   lwd = 3, 
                                   #arr.pos: 
                                   ### where along line arrow
                                   arr.pos = 0.65, 
                                  arr.type = "triangle",
                                  endhead = T,
                                   arr.length = 0.75) 
}


# Make boxes/cirecls and Label 1st plot elements
## ellipse
textellipse(elpos[1,], 0.1, 
                       lab = "start", 
                       box.col = "green",
                       #shadow.col = "darkgreen", 
                       shadow.size = 0.00, 
                       cex = 1.5)
 ## rectancle         
textrect(elpos[2,], 
         0.15, 
         0.05,
         lab = "found term?", 
         #box.col = "blue",
         shadow.col = "darkblue", 
         shadow.size = 0, 
         cex = 1.5)

#rest of plotting elements
textrect (elpos[4,], 0.15, 0.05,lab = "related?", box.col = "blue",
shadow.col = "darkblue", shadow.size = 0.005, cex = 1.5)
textellipse(elpos[3,], 0.1, 0.1, lab = c("other","term"), box.col = "orange",
            shadow.col = "red", shadow.size = 0.005, cex = 1.5)
textellipse(elpos[3,], 0.1, 0.1, lab = c("other","term"), box.col = "orange",
shadow.col = "red", shadow.size = 0.005, cex = 1.5)
textellipse(elpos[7,], 0.1, 0.1, lab = c("make","a link"),box.col = "orange",
shadow.col = "red", shadow.size = 0.005, cex = 1.5)
textellipse(elpos[8,], 0.1, 0.1, lab = c("new","article"),box.col = "orange",
shadow.col = "red", shadow.size = 0.005, cex = 1.5)

# Label arrows
## dd = ?
dd <- c(0.0, 0.025)
text(arrpos[2, 1] + 0.05, arrpos[2, 2], "yes")
text(arrpos[3, 1] - 0.05, arrpos[3, 2], "no")
text(arrpos[4, 1] + 0.05, arrpos[4, 2] + 0.05, "yes")
text(arrpos[5, 1] - 0.05, arrpos[5, 2] + 0.05, "no")
#
```














# My example


```{r}
library(diagram)

#Set margins
par(mar = c(1, 1, 1, 1))

#create empty plot window
openplotmat()

#coordinates estimtes location of plot elemens
## pos = is a vector of the number of elements PER ROW
elpos <- coordinates(pos = c(1, 3,3))

#..
fromto <- matrix(ncol = 2, byrow = TRUE,
                 data = c(1, 2,
                          1, 3,
                          1, 4,
                          2, 5,
                          3, 6,
                          4, 7)) 

#number of rows
nr <- nrow(fromto)

#matrix to hold arrow positions
arrpos <- matrix(ncol = 2, nrow = nr)


#loop to calculate arrow positions and plot them
for (i in 1:nr){
   arrpos[i, ] <- straightarrow(to   = elpos[fromto[i, 2], ],
                                from = elpos[fromto[i, 1], ],
                                   lwd = 3, 
                                   #arr.pos: 
                                   ### where along line arrow
                                   arr.pos = 0.65, 
                                   arr.type = "triangle",
                                  #endhead = T,
                                   arr.length = 0.75) 
}


# Make boxes/cirecls and Label 1st plot elements
## ellipse
### radx = "horizondal radius of the box"
#   rady = vert
makebox <- function(i.elpos = 1, 
                    lab. = "label",
                    radx. = 0.1, 
                    cex. = 1.5,
                    pos. = NULL,
                    lcol. = 1){
  textrect(elpos[i.elpos,], 
         radx = radx., 
         lab = lab., 
         shadow.size = 0.00, 
         cex = cex.,
         pos = pos.,
         lcol = lcol.)
}


#Top
makebox(i.elpos = 1, lab. = "Regression\nModelling")

#Middle row
makebox(i.elpos = 2, lab. = "Model\nfitting")
makebox(i.elpos = 3, lab. = "Model\nDiagnostics")
makebox(i.elpos = 4, lab. = "Inference")

#Bottom row
makebox(i.elpos = 5, lab. = "*Least squares (LS)\n*Maximum likelihood\n*Bayesian", lcol. = 0, pos. = NULL)
makebox(i.elpos = 6, lab. = "*Normaliy\n*Constance variance\n*Independence\n*etc...", lcol. = 0, pos. = NULL)

makebox(i.elpos = 7, lab. = "*Frequentist (t,F,p,CIs)\n*IT-AIC\n*Bayesian", lcol. = 0, pos. = NULL)


```